### ISSUE TITLE
Properties not translated to react properly

### ISSUE THREAD

**Issue by cheryly279** [1stdibs/dibs-vg#172]
Hi Guys,

I am getting this warning using the zoom-in and zoom-out icons. It looks like fill-opacity isn't being translated to fillOpacity when the svg code is react-ified. It's just a warning so not a big deal, but would be nice if we could resolve!

Thanks,
Cheryl

![screen shot 2018-09-19 at 5 18 02 pm](https://user-images.githubusercontent.com/1900816/45782347-9b044300-bc30-11e8-8065-f0086b0d117b.png)

**Comment by hellatan** [comment]
closed by https://github.com/1stdibs/dibs-vg/pull/176
